dict={"physics":75,"chemistry":87,"maths":91,"biology":92}
print("copy method")
copydict=dict.copy()
print(copydict)
print("get method")
print(dict.get("maths"))
print("items() method")
print(dict.items())
print("keys() method")
print(dict.keys())
print("pop methd")
print(dict.pop("chemistry"))
print(dict)
print("values() method")
print(dict.values())
print("update method")
dictone={"lab":30}
dict.update(dictone)
print(dict)
print("clear method")
print(dict.clear())
