tupleone = ("hockey","cricket","tennis","athletics","football")
print(tupleone)
for x in tupleone:
    print(x)
print("accessing tuple elemets")
print(tupleone[0])
print(tupleone[-1])
print("tuple lenght using len() method")
print(len(tupleone))
print("type method")
print(type(tupleone))
print("range of indexes")
print(tupleone[2:5])
print("count method")
print(tupleone.count("hockey"))
print("index method")
print(tupleone.index("tennis"))
